### ISSUE TITLE
Operation statements cannot be rendered in this plugin

### ISSUE THREAD

**Issue by Nitcloud** [1354092549/vscode-markdown-tinymind#4]
Operation statements cannot be rendered in this plugin. How can I solve this problem? My OS is win10.
![TIM截图20200807023751.png](https://i.loli.net/2020/08/07/dChvNJRw2fm8PEz.png)

**Comment by ArcticLampyrid** [comment]
Install a markdown math extension that supports inline math expression first.
This extension doesn't provide any math expression renderer

**Comment by Nitcloud** [comment]
It works，thanks
